# https://docs.github.com/en/actions/guides/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron:  '17 14 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Each version of Node.js specified in the node-version array creates a job that runs the same steps.
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: node --version && npm --version

  check-package-lock:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Each version of Node.js specified in the node-version array creates a job that runs the same steps.
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: node --version && npm --version
      - run: npm install
      - name: Fail if npm install changed package-lock.json
        run: git diff --exit-code package-lock.json
  
  send-email:
    needs: [build, check-package-lock]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Send mail
        uses: dawidd6/action-send-mail@v3.7.1
        if: ${{ needs.build.result == 'failure' || needs.check-package-lock.result == 'failure' }}
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_ADDR }}
          from: ${{ secrets.MAIL_ADDR }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: Job status of ${{ github.repository }} [FAILED]
          body: |
            ${{ github.workflow }} of ${{ github.repository }}
            -> BUILD job status - ${{ needs.build.result }}
            -> CHECK PACKAGE LOCK job status - ${{ needs.check-package-lock.result }}
                
          to: ${{ secrets.MAIL_TO }}
