# https://docs.github.com/en/actions/guides/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron:  '11 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Each version of Node.js specified in the node-version array creates a job that runs the same steps.
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: node --version && npm --version
      - run: npm ci
      - run: npm run build
      - run: npm test

  check-package-lock:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Each version of Node.js specified in the node-version array creates a job that runs the same steps.
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: node --version && npm --version
      - run: npm install
      - name: Fail if npm install changed package-lock.json
        run: git diff --exit-code package-lock.json
